//! Parses, validates, and prepares Debian changelog entries.

use std::{fs, path::Path, path::PathBuf, process::Command};

use anyhow::{Context, Result, bail};
use debian_changelog::ChangeLog;

const LEGACY_UNRELEASED: &str = "UNRELEASED-FIXME-AUTOGENERATED-DEBCARGO";

/// Parsed fields from the first Debian changelog entry.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TopChangelog {
    /// Debian source package name.
    pub source: String,
    /// Complete Debian source version.
    pub version: String,
    /// Debian upstream version without epoch or Debian revision.
    pub upstream: String,
    /// Distribution named by the top entry.
    pub distribution: String,
}

/// Changelog operation delegated to `dch`.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum ChangelogAction {
    /// Create the first changelog entry.
    Create,
    /// Increment a released entry for the same upstream version.
    Increment,
    /// Select a specified upstream version.
    NewVersion,
    /// Retain and update the current unreleased entry.
    Append,
}

/// Parses only the first Debian changelog header.
pub fn read_top_changelog(path: &Path) -> Result<TopChangelog> {
    let changelog =
        ChangeLog::read_path(path).with_context(|| format!("read {}", path.display()))?;
    parse_top_changelog(&changelog).with_context(|| format!("parse {}", path.display()))
}

/// Requires the top changelog upstream to describe the current root Cargo release.
pub fn validate_top_changelog(
    top: &TopChangelog,
    cargo_version: &str,
    cargo_upstream: &str,
) -> Result<()> {
    if top.upstream != cargo_upstream
        && !top
            .upstream
            .strip_prefix(cargo_upstream)
            .is_some_and(|suffix| suffix.starts_with('+') && suffix.len() > 1)
    {
        bail!(
            "top changelog upstream {} does not describe root Cargo version {}",
            top.upstream,
            cargo_version
        );
    }
    Ok(())
}

/// Prepares changelog with `dch`, then normalizes its top entry.
pub fn prepare_changelog(
    old_path: Option<PathBuf>,
    staged_path: &Path,
    old_top: Option<&TopChangelog>,
    source_name: &str,
    upstream: &str,
    provenance: &str,
) -> Result<()> {
    if let Some(old_path) = old_path {
        fs::copy(&old_path, staged_path)
            .with_context(|| format!("copy {} to {}", old_path.display(), staged_path.display()))?;
    }
    let initial_version = format!("{upstream}-0ubuntu1");
    let action = select_changelog_action(old_top, upstream);
    let mut command = Command::new("dch");
    command
        .arg("--no-conf")
        .arg("--vendor")
        .arg("Ubuntu")
        .arg("--changelog")
        .arg(staged_path)
        .arg("--check-dirname-level")
        .arg("0")
        .arg("--distribution")
        .arg("UNRELEASED")
        .arg("--force-distribution");
    match action {
        ChangelogAction::Create => {
            command
                .arg("--create")
                .arg("--package")
                .arg(source_name)
                .arg("--newversion")
                .arg(&initial_version);
        }
        ChangelogAction::Increment => {
            command.arg("--increment");
        }
        ChangelogAction::NewVersion => {
            command.arg("--newversion").arg(&initial_version);
        }
        ChangelogAction::Append => {
            command.arg("--append");
        }
    }
    let output = command.arg(provenance).output().context("run dch")?;
    if !output.status.success() {
        bail!(
            "dch failed:\n{}{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
    }

    let mut changelog = ChangeLog::read_path(staged_path).context("read prepared changelog")?;
    normalize_top_entry(&mut changelog, provenance)?;
    changelog
        .write_to_path(staged_path)
        .context("write prepared changelog")?;
    let top = read_top_changelog(staged_path)?;
    if top.source != source_name || top.upstream != upstream {
        bail!(
            "prepared changelog identifies {} {}, expected {source_name} {upstream}",
            top.source,
            top.upstream
        );
    }
    Ok(())
}

/// Extracts the top entry fields from a parsed changelog.
fn parse_top_changelog(changelog: &ChangeLog) -> Result<TopChangelog> {
    let entry = changelog.iter().next().context("changelog is empty")?;
    let source = entry.package().context("changelog entry has no source")?;
    let version = entry
        .try_version()
        .transpose()
        .context("parse changelog version")?
        .context("changelog entry has no version")?;
    let distribution = entry
        .distributions()
        .context("changelog entry has no distribution")?
        .join(" ");
    if distribution.trim().is_empty() {
        bail!("changelog entry has no distribution");
    }
    Ok(TopChangelog {
        source,
        version: version.to_string(),
        upstream: version.upstream_version,
        distribution,
    })
}

/// Selects the `dch` action for old and candidate changelog state.
fn select_changelog_action(
    old: Option<&TopChangelog>,
    candidate_upstream: &str,
) -> ChangelogAction {
    let Some(old) = old else {
        return ChangelogAction::Create;
    };
    let unreleased = old.distribution == "UNRELEASED" || old.distribution == LEGACY_UNRELEASED;
    if unreleased && old.upstream == candidate_upstream {
        ChangelogAction::Append
    } else if !unreleased && old.upstream == candidate_upstream {
        ChangelogAction::Increment
    } else {
        ChangelogAction::NewVersion
    }
}

/// Normalizes the top entry distribution and provenance bullet.
fn normalize_top_entry(changelog: &mut ChangeLog, provenance: &str) -> Result<()> {
    let mut entry = changelog.iter().next().context("changelog is empty")?;
    let top_version = entry
        .try_version()
        .transpose()
        .context("parse top changelog version")?
        .context("top changelog entry has no version")?;
    let mut distributions = entry
        .distributions()
        .context("changelog entry has no distribution")?;
    for item in &mut distributions {
        if item == LEGACY_UNRELEASED {
            *item = "UNRELEASED".to_owned();
        }
    }
    entry.set_distributions(distributions);

    let provenance = format!("* {provenance}");
    let mut provenance_bullet = None;
    for change in debian_changelog::iter_changes_by_author(changelog) {
        if change.try_version().transpose()? != Some(top_version.clone()) {
            break;
        }
        for bullet in change.split_into_bullets() {
            if is_provenance(bullet.lines())
                && let Some(previous) = provenance_bullet.replace(bullet)
            {
                previous.remove();
            }
        }
    }
    if let Some(bullet) = provenance_bullet {
        bullet.replace_with(provenance.lines().collect());
    } else {
        for line in provenance.lines().rev() {
            entry.prepend_change_line(line);
        }
    }
    Ok(())
}

/// Checks whether changelog lines identify an Ubucargo/debcargo provenance bullet.
fn is_provenance(lines: Vec<String>) -> bool {
    let Some(first) = lines.first() else {
        return false;
    };
    first.starts_with("* Package ")
        && lines.iter().any(|line| line.contains("from crates.io"))
        && lines.iter().any(|line| line.contains("debcargo"))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Parses changelog text and returns its top entry fields.
    fn parse_text(contents: &str) -> TopChangelog {
        parse_top_changelog(&contents.parse().unwrap()).unwrap()
    }

    #[test]
    /// Verifies top changelog parsing and Cargo-version validation with a repack suffix.
    fn validates_top_changelog_identity() {
        let top = parse_text("rust-example (1.2.3+ds-0ubuntu1) noble; urgency=medium\n");
        validate_top_changelog(&top, "1.2.3", "1.2.3").unwrap();
        assert_eq!(top.source, "rust-example");
        assert_eq!(top.upstream, "1.2.3+ds");
    }

    #[test]
    /// Verifies changelog action selection for released and unreleased entries.
    fn selects_changelog_actions() {
        let mut top = parse_text("rust-example (1.2.3-0ubuntu1) noble; urgency=medium\n");
        assert_eq!(
            select_changelog_action(Some(&top), "1.2.3"),
            ChangelogAction::Increment
        );
        assert_eq!(
            select_changelog_action(Some(&top), "2.0.0"),
            ChangelogAction::NewVersion
        );
        top.distribution = "UNRELEASED".to_owned();
        assert_eq!(
            select_changelog_action(Some(&top), "1.2.3"),
            ChangelogAction::Append
        );
        assert_eq!(
            select_changelog_action(None, "1.2.3"),
            ChangelogAction::Create
        );
    }

    #[test]
    /// Verifies provenance replacement and legacy unreleased normalization.
    fn replaces_provenance_once() {
        let old = concat!(
            "rust-example (1.0.0-1) UNRELEASED-FIXME-AUTOGENERATED-DEBCARGO; urgency=medium\n",
            "\n",
            "  * Package example 1.0.0 from crates.io using debcargo 2.7.0\n",
            "    with an old wrapped continuation.\n",
            "  * local change\n",
            "  * Package example 1.0.0 from crates.io using debcargo 2.8.0 and ubucargo 0.0.1.\n",
            "  * Package example 1.0.0 from crates.io.   Generated with debcargo\n",
            "    2.8.4 and ubucargo 0.1.0.\n",
            "\n",
            " -- A <a@example.com>  Mon, 01 Jan 2024 00:00:00 +0000\n",
            "\n",
            "rust-example (0.9.0-1) unstable; urgency=medium\n",
            "\n",
            "  * Package example 0.9.0 from crates.io using debcargo 2.7.0\n",
            "\n",
            " -- B <b@example.com>  Sun, 31 Dec 2023 00:00:00 +0000\n"
        );
        let mut changelog: ChangeLog = old.parse().unwrap();
        normalize_top_entry(
            &mut changelog,
            "Package example 1.0.0 from crates.io.\n  Generated with debcargo 2.8.4 and ubucargo 0.1.0.",
        )
        .unwrap();
        let new = changelog.to_string();
        assert!(new.contains(") UNRELEASED;"));
        assert_eq!(new.matches("debcargo").count(), 2);
        assert!(new.contains("* Package example 0.9.0 from crates.io using debcargo 2.7.0"));
        assert!(new.contains("  * local change"));
        assert!(new.contains(concat!(
            "  * Package example 1.0.0 from crates.io.\n",
            "    Generated with debcargo 2.8.4 and ubucargo 0.1.0."
        )));
    }
}
