use std::{fs, path::Path, path::PathBuf, process::Command};

use anyhow::{Context, Result, bail};

const DEBCARGO_VERSION_NUMBER: &str = "2.8.4";
const LEGACY_UNRELEASED: &str = "UNRELEASED-FIXME-AUTOGENERATED-DEBCARGO";

/// Parsed fields from the first Debian changelog entry.
#[derive(Clone, Debug, Eq, PartialEq)]
pub(super) struct TopChangelog {
    /// Debian source package name.
    pub(super) source: String,
    /// Complete Debian source version.
    pub(super) version: String,
    /// Debian upstream version without epoch or Debian revision.
    pub(super) upstream: String,
    /// Distribution named by the top entry.
    pub(super) distribution: String,
}

/// Changelog operation delegated to `dch`.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum ChangelogAction {
    /// Create the first changelog entry.
    Create,
    /// Increment a released entry for the same upstream version.
    Increment,
    /// Select a specified upstream version.
    NewVersion,
    /// Retain and update the current unreleased entry.
    Append,
}

/// Parses only the first Debian changelog header.
pub(super) fn read_top_changelog(path: &Path) -> Result<TopChangelog> {
    let contents = fs::read_to_string(path).with_context(|| format!("read {}", path.display()))?;
    parse_top_changelog(&contents).with_context(|| format!("parse {}", path.display()))
}

/// Requires the top changelog upstream to describe the current root Cargo release.
pub(super) fn validate_top_changelog(
    top: &TopChangelog,
    cargo_version: &str,
    cargo_upstream: &str,
) -> Result<()> {
    if top.upstream != cargo_upstream
        && !top
            .upstream
            .strip_prefix(cargo_upstream)
            .is_some_and(|suffix| suffix.starts_with('+') && suffix.len() > 1)
    {
        bail!(
            "top changelog upstream {} does not describe root Cargo version {}",
            top.upstream,
            cargo_version
        );
    }
    Ok(())
}

/// Prepares changelog with `dch`, then normalizes its top entry.
pub(super) fn prepare_changelog(
    old_path: Option<PathBuf>,
    staged_path: &Path,
    old_top: Option<&TopChangelog>,
    source_name: &str,
    upstream: &str,
    crate_name: &str,
    crate_version: &str,
) -> Result<()> {
    if let Some(old_path) = old_path {
        fs::copy(&old_path, staged_path)
            .with_context(|| format!("copy {} to {}", old_path.display(), staged_path.display()))?;
    }
    let initial_version = format!("{upstream}-0ubuntu1");
    let provenance = format!(
        "Package {crate_name} {crate_version} from crates.io using debcargo {} and ubucargo {}.",
        DEBCARGO_VERSION_NUMBER,
        env!("CARGO_PKG_VERSION")
    );
    let action = select_changelog_action(old_top, upstream);
    let mut command = Command::new("dch");
    command
        .arg("--no-conf")
        .arg("--vendor")
        .arg("Ubuntu")
        .arg("--changelog")
        .arg(staged_path)
        .arg("--check-dirname-level")
        .arg("0")
        .arg("--distribution")
        .arg("UNRELEASED")
        .arg("--force-distribution");
    match action {
        ChangelogAction::Create => {
            command
                .arg("--create")
                .arg("--package")
                .arg(source_name)
                .arg("--newversion")
                .arg(&initial_version);
        }
        ChangelogAction::Increment => {
            command.arg("--increment");
        }
        ChangelogAction::NewVersion => {
            command.arg("--newversion").arg(&initial_version);
        }
        ChangelogAction::Append => {
            command.arg("--append");
        }
    }
    let output = command.arg(&provenance).output().context("run dch")?;
    if !output.status.success() {
        bail!(
            "dch failed:\n{}{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
    }

    let contents = fs::read_to_string(staged_path)?;
    let contents = replace_provenance(&contents, &format!("  * {provenance}"));
    fs::write(staged_path, contents)?;
    let top = read_top_changelog(staged_path)?;
    if top.source != source_name || top.upstream != upstream {
        bail!(
            "prepared changelog identifies {} {}, expected {source_name} {upstream}",
            top.source,
            top.upstream
        );
    }
    Ok(())
}

/// Parses the source, version, distribution, and upstream version from a changelog header.
fn parse_top_changelog(contents: &str) -> Result<TopChangelog> {
    let header = contents.lines().next().context("changelog is empty")?;
    let (source, rest) = header
        .split_once(" (")
        .context("invalid changelog header")?;
    let (version, rest) = rest.split_once(") ").context("invalid changelog version")?;
    let (distribution, _) = rest
        .split_once(';')
        .context("invalid changelog distribution")?;
    if source.is_empty() || version.is_empty() || distribution.trim().is_empty() {
        bail!("invalid changelog header");
    }
    let upstream = debian_upstream_version(version)?;
    Ok(TopChangelog {
        source: source.to_owned(),
        version: version.to_owned(),
        upstream,
        distribution: distribution.trim().to_owned(),
    })
}

/// Extracts the epoch-free upstream portion from a Debian source version.
fn debian_upstream_version(version: &str) -> Result<String> {
    let without_epoch = version.split_once(':').map_or(version, |(_, value)| value);
    let (upstream, revision) = without_epoch
        .rsplit_once('-')
        .context("Debian source version has no revision")?;
    if upstream.is_empty() || revision.is_empty() {
        bail!("invalid Debian source version {version}");
    }
    Ok(upstream.to_owned())
}

/// Selects the `dch` action for old and candidate changelog state.
fn select_changelog_action(
    old: Option<&TopChangelog>,
    candidate_upstream: &str,
) -> ChangelogAction {
    let Some(old) = old else {
        return ChangelogAction::Create;
    };
    let unreleased = old.distribution == "UNRELEASED" || old.distribution == LEGACY_UNRELEASED;
    if unreleased && old.upstream == candidate_upstream {
        ChangelogAction::Append
    } else if !unreleased && old.upstream == candidate_upstream {
        ChangelogAction::Increment
    } else {
        ChangelogAction::NewVersion
    }
}

/// Replaces all Ubucargo/debcargo provenance lines in the top changelog entry with one line.
fn replace_provenance(contents: &str, provenance: &str) -> String {
    let had_trailing_newline = contents.ends_with('\n');
    let mut lines: Vec<String> = contents.lines().map(str::to_owned).collect();
    if let Some(header) = lines.first_mut() {
        *header = header.replace(LEGACY_UNRELEASED, "UNRELEASED");
    }
    let mut top_end = lines.len();
    for (index, line) in lines.iter().enumerate().skip(1) {
        if !line.is_empty() && !line.starts_with(char::is_whitespace) {
            top_end = index;
            break;
        }
    }

    let mut rewritten = Vec::new();
    let mut found = false;
    let mut index = 0;
    while index < top_end {
        let trimmed = lines[index].trim_start();
        if trimmed.starts_with("* Package ") && trimmed.contains(" using debcargo ") {
            if !found {
                rewritten.push(provenance.to_owned());
                found = true;
            }
            index += 1;
            while index < top_end && lines[index].starts_with("    ") {
                index += 1;
            }
            continue;
        }
        rewritten.push(lines[index].clone());
        index += 1;
    }
    rewritten.extend(lines.into_iter().skip(top_end));
    lines = rewritten;
    if !found {
        let insert = if lines.get(1).is_some_and(|line| line.is_empty()) {
            2
        } else {
            1
        };
        lines.insert(insert, provenance.to_owned());
    }
    let mut result = lines.join("\n");
    if had_trailing_newline {
        result.push('\n');
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    /// Verifies top changelog parsing and Cargo-version validation with a repack suffix.
    fn validates_top_changelog_identity() {
        let top = parse_top_changelog("rust-example (1.2.3+ds-0ubuntu1) noble; urgency=medium\n")
            .unwrap();
        validate_top_changelog(&top, "1.2.3", "1.2.3").unwrap();
        assert_eq!(top.source, "rust-example");
        assert_eq!(top.upstream, "1.2.3+ds");
    }

    #[test]
    /// Verifies changelog action selection for released and unreleased entries.
    fn selects_changelog_actions() {
        let mut top =
            parse_top_changelog("rust-example (1.2.3-0ubuntu1) noble; urgency=medium\n").unwrap();
        assert_eq!(
            select_changelog_action(Some(&top), "1.2.3"),
            ChangelogAction::Increment
        );
        assert_eq!(
            select_changelog_action(Some(&top), "2.0.0"),
            ChangelogAction::NewVersion
        );
        top.distribution = "UNRELEASED".to_owned();
        assert_eq!(
            select_changelog_action(Some(&top), "1.2.3"),
            ChangelogAction::Append
        );
        assert_eq!(
            select_changelog_action(None, "1.2.3"),
            ChangelogAction::Create
        );
    }

    #[test]
    /// Verifies provenance replacement and legacy unreleased normalization.
    fn replaces_provenance_once() {
        let old = concat!(
            "rust-example (1.0.0-1) UNRELEASED-FIXME-AUTOGENERATED-DEBCARGO; urgency=medium\n",
            "\n",
            "  * Package example 1.0.0 from crates.io using debcargo 2.7.0\n",
            "    with an old wrapped continuation.\n",
            "  * local change\n",
            "  * Package example 1.0.0 from crates.io using debcargo 2.8.0 and ubucargo 0.0.1.\n",
            "\n",
            " -- A <a@example.com>  Mon, 01 Jan 2024 00:00:00 +0000\n"
        );
        let new = replace_provenance(
            old,
            "  * Package example 1.0.0 from crates.io using debcargo 2.8.4 and ubucargo 0.1.0.",
        );
        assert!(new.contains(") UNRELEASED;"));
        assert_eq!(new.matches("using debcargo").count(), 1);
        assert!(new.contains("  * local change"));
    }
}
