use std::{
    collections::{BTreeMap, BTreeSet},
    ffi::OsStr,
    fs::{self, File},
    io::{Read, Write},
    os::unix::fs::{PermissionsExt, symlink},
    path::{Path, PathBuf},
    process::Command,
};

use anyhow::{Context, Result, bail};
use fs2::FileExt;
use semver::Version;
use serde::Deserialize;
use tempfile::{NamedTempFile, TempDir};
use toml_edit::{DocumentMut, value};

use crate::materialize::{FileState, PathPlan, build_plan, make_hint_path, read_state};

const DEBCARGO_VERSION: &str = "debcargo 2.8.4";
const DEBCARGO_VERSION_NUMBER: &str = "2.8.4";
const LEGACY_UNRELEASED: &str = "UNRELEASED-FIXME-AUTOGENERATED-DEBCARGO";
const PACKAGE_MANAGED_PATHS: &[&str] = &[
    "debian/cargo-checksum.json",
    "debian/control",
    "debian/copyright",
    "debian/rules",
    "debian/source/format",
    "debian/tests/control",
    "debian/upstream/metadata",
    "debian/watch",
];
const EXPECTED_UNMANAGED_OUTPUTS: &[&str] = &["debian/changelog"];

/// Relevant package records returned by `cargo metadata`.
#[derive(Deserialize)]
struct Metadata {
    /// Cargo packages contained in the staged workspace.
    packages: Vec<MetadataPackage>,
}

/// Cargo metadata needed to identify the staged root package.
#[derive(Clone, Debug, Deserialize)]
pub(crate) struct MetadataPackage {
    /// Cargo package name passed to debcargo.
    pub(crate) name: String,
    /// Exact Cargo package version passed to debcargo.
    pub(crate) version: String,
    /// Manifest used to distinguish the root package from workspace members.
    manifest_path: PathBuf,
}

/// Filesystem target selected for a package operation.
#[derive(Debug, Eq, PartialEq)]
enum Target {
    /// An existing Ubucargo source package.
    Existing(PathBuf),
    /// A clean destination that does not yet exist.
    New {
        /// Directory that will contain the source package and orig tarball.
        parent: PathBuf,
        /// Explicit source directory, or none when the Debian source name is used.
        requested: Option<PathBuf>,
    },
}

/// Debcargo configuration values that affect package identity.
struct PackageConfig {
    /// Complete in-tree configuration text.
    contents: String,
    /// Whether the Debian source name includes the crate's semver line.
    semver_suffix: bool,
    /// Effective repack suffix, including debcargo's default for exclusions.
    repack_suffix: Option<String>,
}

/// Parsed fields from the first Debian changelog entry.
#[derive(Clone, Debug, Eq, PartialEq)]
struct TopChangelog {
    /// Debian source package name.
    source: String,
    /// Complete Debian source version.
    version: String,
    /// Debian upstream version without epoch or Debian revision.
    upstream: String,
    /// Distribution named by the top entry.
    distribution: String,
}

/// Exact crate release selected for final generation.
struct Selection {
    /// Canonical crate name reported by Cargo.
    crate_name: String,
    /// Exact Cargo semver string reported by Cargo.
    version: String,
}

/// Validated files and identities produced by final debcargo generation.
struct GeneratedOutput {
    /// Staged source package tree.
    source: PathBuf,
    /// Staged Debian orig tarball.
    orig: PathBuf,
    /// Debian source package name.
    debian_source: String,
}

/// An old orig path and any temporary directory that keeps it alive.
struct OrigBaseline {
    /// Existing or downloaded orig tarball.
    path: PathBuf,
    /// Download directory, retained until reconciliation is complete.
    _temporary: Option<TempDir>,
}

/// Changelog operation delegated to `dch`.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum ChangelogAction {
    /// Create the first changelog entry.
    Create,
    /// Increment a released entry for the same upstream version.
    Increment,
    /// Select a specified upstream version.
    NewVersion,
    /// Retain and update the current unreleased entry.
    Append,
}

/// Source-tree entry relevant to three-way reconciliation.
#[derive(Clone, Debug, Eq, PartialEq)]
enum TreeNode {
    /// Directory with its Unix permission mode.
    Directory(u32),
    /// Regular file contents and Unix permission mode.
    File(FileState),
    /// Symbolic-link target.
    Symlink(PathBuf),
}

/// Complete source-tree update outside `debian/`.
struct SourcePlan {
    /// Deterministic path transitions.
    paths: BTreeMap<PathBuf, (Option<TreeNode>, Option<TreeNode>)>,
}

impl SourcePlan {
    /// Reports whether applying the source plan changes any path.
    fn has_changes(&self) -> bool {
        for (old, new) in self.paths.values() {
            if old != new {
                return true;
            }
        }
        false
    }

    /// Prints source-tree changes in deterministic path order.
    fn print_report(&self) {
        for (path, (old, new)) in &self.paths {
            if old == new {
                continue;
            }
            let verb = match (old, new) {
                (None, Some(_)) => "create",
                (Some(_), None) => "remove",
                _ => "update",
            };
            println!("{verb} {}", path.display());
        }
    }

    /// Applies validated source transitions without recursively deleting paths.
    fn apply(&self, root: &Path) -> Result<()> {
        let mut paths = Vec::new();
        for (path, states) in &self.paths {
            if states.0 != states.1 {
                paths.push(path);
            }
        }
        paths.sort_by_key(|path| std::cmp::Reverse(path.components().count()));

        for path in &paths {
            let (old, new) = self.paths.get(*path).unwrap();
            let remove = match (old, new) {
                (Some(TreeNode::Directory(_)), Some(TreeNode::Directory(_))) => false,
                (Some(TreeNode::File(_)), Some(TreeNode::File(_))) => false,
                (Some(_), _) => true,
                _ => false,
            };
            if !remove || matches!(old, Some(TreeNode::Directory(_))) {
                continue;
            }
            fs::remove_file(root.join(path))
                .with_context(|| format!("remove {}", root.join(path).display()))?;
        }
        for path in &paths {
            let (old, new) = self.paths.get(*path).unwrap();
            if matches!(old, Some(TreeNode::Directory(_)))
                && !matches!(new, Some(TreeNode::Directory(_)))
            {
                fs::remove_dir(root.join(path))
                    .with_context(|| format!("remove {}", root.join(path).display()))?;
            }
        }

        paths.sort_by_key(|path| path.components().count());
        for path in &paths {
            let (old, new) = self.paths.get(*path).unwrap();
            if matches!(new, Some(TreeNode::Directory(_)))
                && !matches!(old, Some(TreeNode::Directory(_)))
            {
                fs::create_dir(root.join(path))
                    .with_context(|| format!("create {}", root.join(path).display()))?;
            }
        }
        for path in &paths {
            let destination = root.join(path);
            let (old, new) = self.paths.get(*path).unwrap();
            match new {
                Some(TreeNode::File(state)) if old != new => {
                    install_regular_file(&destination, state)?;
                }
                Some(TreeNode::Symlink(target)) if old != new => {
                    symlink(target, &destination)
                        .with_context(|| format!("create symlink {}", destination.display()))?;
                }
                _ => {}
            }
        }
        for path in &paths {
            if let Some(TreeNode::Directory(mode)) = self.paths.get(*path).unwrap().1 {
                fs::set_permissions(root.join(path), fs::Permissions::from_mode(mode))
                    .with_context(|| format!("set mode for {}", root.join(path).display()))?;
            }
        }
        Ok(())
    }
}

/// Creates or reconciles one source package, returning true when check mode finds changes.
pub fn run(
    crate_name: Option<&str>,
    version: Option<&str>,
    directory: Option<&Path>,
    check: bool,
    force: bool,
    keep: &[PathBuf],
    replace: &[PathBuf],
) -> Result<bool> {
    if version.is_some() && crate_name.is_none() {
        bail!("VERSION requires CRATE");
    }
    if let Some(version) = version {
        parse_exact_version(version)?;
    }

    let current = std::env::current_dir()
        .context("get current directory")?
        .canonicalize()
        .context("resolve current directory")?;
    let target = resolve_target(&current, directory, crate_name.is_some())?;
    let lock_path = match &target {
        Target::Existing(root) => root.join("debian"),
        Target::New { parent, .. } => find_existing_ancestor(parent)?,
    };
    let lock = File::open(&lock_path).with_context(|| format!("open {}", lock_path.display()))?;
    if let Err(error) = lock.try_lock_exclusive() {
        if error.kind() == std::io::ErrorKind::WouldBlock {
            bail!("another package operation is using {}", lock_path.display());
        }
        return Err(error).with_context(|| format!("lock {}", lock_path.display()));
    }

    let (keep_paths, replace_paths) = collect_decisions(keep, replace)?;
    check_debcargo_version()?;
    match target {
        Target::Existing(root) => reconcile_existing(
            &root,
            crate_name,
            version,
            check,
            force,
            &keep_paths,
            &replace_paths,
        ),
        Target::New { parent, requested } => {
            if !keep_paths.is_empty() || !replace_paths.is_empty() {
                bail!("--keep and --replace apply only to existing packages");
            }
            let crate_name = crate_name.context("CRATE is required when creating a package")?;
            create_new(&parent, requested.as_deref(), crate_name, version, check)
        }
    }
}

/// Resolves explicit and implicit package modes without inheriting an enclosing package for a new explicit path.
fn resolve_target(start: &Path, directory: Option<&Path>, has_crate: bool) -> Result<Target> {
    if let Some(directory) = directory {
        let requested = if directory.is_absolute() {
            directory.to_path_buf()
        } else {
            start.join(directory)
        };
        match fs::symlink_metadata(&requested) {
            Ok(metadata) if metadata.is_dir() => {
                let root = requested
                    .canonicalize()
                    .with_context(|| format!("resolve {}", requested.display()))?;
                if !has_debcargo_config(&root) {
                    bail!(
                        "{} is not a source-package root with debian/debcargo.toml",
                        root.display()
                    );
                }
                return Ok(Target::Existing(root));
            }
            Ok(_) => bail!("{} is not a directory", requested.display()),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
                if !has_crate {
                    bail!("CRATE is required when creating {}", requested.display());
                }
                let parent = requested
                    .parent()
                    .with_context(|| format!("{} has no parent", requested.display()))?
                    .to_path_buf();
                return Ok(Target::New {
                    parent,
                    requested: Some(requested),
                });
            }
            Err(error) => {
                return Err(error).with_context(|| format!("inspect {}", requested.display()));
            }
        }
    }

    for candidate in start.ancestors() {
        if has_debcargo_config(candidate) {
            return Ok(Target::Existing(candidate.to_path_buf()));
        }
    }
    if !has_crate {
        bail!(
            "{} is not inside a source package; CRATE is required to create one",
            start.display()
        );
    }
    Ok(Target::New {
        parent: start.to_path_buf(),
        requested: None,
    })
}

/// Finds the nearest existing directory used to serialize creation.
fn find_existing_ancestor(path: &Path) -> Result<PathBuf> {
    for candidate in path.ancestors() {
        if candidate.is_dir() {
            return candidate
                .canonicalize()
                .with_context(|| format!("resolve {}", candidate.display()));
        }
    }
    bail!("{} has no existing parent directory", path.display())
}

/// Reports whether a directory contains Ubucargo's source-package marker.
fn has_debcargo_config(path: &Path) -> bool {
    path.join("debian/debcargo.toml").is_file()
}

/// Validates and deduplicates generated-file decisions.
fn collect_decisions(
    keep: &[PathBuf],
    replace: &[PathBuf],
) -> Result<(BTreeSet<PathBuf>, BTreeSet<PathBuf>)> {
    let mut keep_paths = BTreeSet::new();
    for path in keep {
        keep_paths.insert(path.clone());
    }
    let mut replace_paths = BTreeSet::new();
    for path in replace {
        replace_paths.insert(path.clone());
    }
    if let Some(path) = keep_paths.intersection(&replace_paths).next() {
        bail!(
            "{} cannot be named by both --keep and --replace",
            path.display()
        );
    }
    Ok((keep_paths, replace_paths))
}

/// Reconciles an existing package against one exact crate release.
fn reconcile_existing(
    root: &Path,
    requested_name: Option<&str>,
    requested_version: Option<&str>,
    check: bool,
    force: bool,
    keep: &BTreeSet<PathBuf>,
    replace: &BTreeSet<PathBuf>,
) -> Result<bool> {
    let debian = root.join("debian");
    let current_package = read_root_package(root)?;
    let top = read_top_changelog(&debian.join("changelog"))?;
    validate_top_changelog(&top, &current_package)?;
    let config = read_package_config(&debian.join("debcargo.toml"))?;
    let selection = select_release(
        requested_name,
        requested_version,
        Some(&current_package),
        &config,
    )?;
    let selected_version = parse_exact_version(&selection.version)?;
    let upstream = cargo_to_debian_version(&selected_version, config.repack_suffix.as_deref());
    let source_name = crate_source_name(
        &selection.crate_name,
        &selected_version,
        config.semver_suffix,
    );
    if source_name != top.source {
        bail!(
            "selected crate maps to Debian source {source_name}, not existing source {}",
            top.source
        );
    }

    let old_orig = acquire_old_orig(root, &top)?;
    let base = tempfile::tempdir().context("create old-source extraction directory")?;
    extract_orig(&old_orig.path, base.path())?;
    let patches_applied = check_patch_state(root)?;

    let stage = stage_candidate(
        &config,
        Some(&debian),
        Some(&top),
        &source_name,
        &upstream,
        &selection,
    )?;
    let output = validate_output(
        stage.path(),
        &source_name,
        &upstream,
        &selection.crate_name,
        &selection.version,
    )?;

    let base_tree = scan_tree(base.path(), false)?;
    let old_tree = scan_tree(root, true)?;
    let new_tree = scan_tree(&output.source, true)?;
    let source_changed = base_tree != new_tree;
    if source_changed && patches_applied {
        bail!("pop the complete quilt stack before reconciling changed upstream source");
    }
    let source_plan = build_source_plan(&base_tree, &old_tree, &new_tree, force)?;

    let generated = read_generated_candidates(stage.path())?;
    let managed = collect_managed_paths(&debian, &generated)?;
    let mut generated_plan = build_plan(&debian, &managed, &generated, keep, replace)?;
    generated_plan
        .paths
        .push(build_patch_series_plan(&debian, stage.path())?);
    let ambiguities = generated_plan.collect_ambiguities();
    if !ambiguities.is_empty() {
        for path in ambiguities {
            println!("ambiguous {} (use --keep or --replace)", path.display());
        }
        bail!("unresolved generated-file ambiguities");
    }

    let prepared_changelog = read_state(&stage.path().join("overlay/changelog"))?
        .context("staged changelog is missing")?;
    let old_changelog = read_state(&debian.join("changelog"))?;
    let changelog_changed = old_changelog.as_ref() != Some(&prepared_changelog);
    let orig_destination = root.parent().context("package root has no parent")?.join(
        output
            .orig
            .file_name()
            .context("candidate orig has no file name")?,
    );
    let orig_changed = validate_candidate_orig(&output.orig, &orig_destination)?;

    if orig_changed {
        println!("create {}", orig_destination.display());
    }
    source_plan.print_report();
    generated_plan.print_report();
    if changelog_changed {
        println!("update debian/changelog");
    }

    let generated_changed = generated_plan.has_changes();
    if patches_applied && generated_patch_changes(&generated_plan) && !check {
        bail!("pop the real quilt stack before applying generated patch changes");
    }
    let changed =
        orig_changed || source_plan.has_changes() || generated_changed || changelog_changed;
    if check {
        if !changed {
            println!("clean");
        }
        return Ok(changed);
    }
    if !changed {
        println!("clean");
        return Ok(false);
    }

    if orig_changed {
        install_orig(&output.orig, &orig_destination)?;
    }
    source_plan
        .apply(root)
        .context("package may be partially updated; rerun `ubucargo package`")?;
    if generated_changed {
        generated_plan.apply()?;
    }
    if changelog_changed {
        install_regular_file(&debian.join("changelog"), &prepared_changelog)?;
    }
    Ok(false)
}

/// Creates a clean package without inheriting any enclosing package state.
fn create_new(
    parent: &Path,
    requested: Option<&Path>,
    crate_name: &str,
    requested_version: Option<&str>,
    check: bool,
) -> Result<bool> {
    let config = read_package_config_text("[ubucargo]\n")?;
    let selection = select_release(Some(crate_name), requested_version, None, &config)?;
    let selected_version = parse_exact_version(&selection.version)?;
    let upstream = cargo_to_debian_version(&selected_version, config.repack_suffix.as_deref());
    let source_name = crate_source_name(
        &selection.crate_name,
        &selected_version,
        config.semver_suffix,
    );
    let stage = stage_candidate(&config, None, None, &source_name, &upstream, &selection)?;
    let output = validate_output(
        stage.path(),
        &source_name,
        &upstream,
        &selection.crate_name,
        &selection.version,
    )?;
    initialize_package(&output.source)?;

    let source = requested
        .map(Path::to_path_buf)
        .unwrap_or_else(|| parent.join(&output.debian_source));
    ensure_destination_absent(&source)?;
    let orig = parent.join(
        output
            .orig
            .file_name()
            .context("candidate orig has no file name")?,
    );
    let orig_changed = validate_candidate_orig(&output.orig, &orig)?;
    println!("create {}", source.display());
    if orig_changed {
        println!("create {}", orig.display());
    }
    if check {
        return Ok(true);
    }

    fs::create_dir_all(parent).with_context(|| format!("create {}", parent.display()))?;
    if orig_changed {
        install_orig(&output.orig, &orig)?;
    }
    install_new_tree(&output.source, &source)?;
    Ok(false)
}

/// Selects an exact release, using preliminary extraction only for latest-version resolution.
fn select_release(
    requested_name: Option<&str>,
    requested_version: Option<&str>,
    current: Option<&MetadataPackage>,
    config: &PackageConfig,
) -> Result<Selection> {
    match (requested_name, requested_version, current) {
        (None, None, Some(current)) => Ok(Selection {
            crate_name: current.name.clone(),
            version: current.version.clone(),
        }),
        (Some(name), Some(version), _) => {
            parse_exact_version(version)?;
            Ok(Selection {
                crate_name: name.to_owned(),
                version: version.to_owned(),
            })
        }
        (Some(name), None, _) => resolve_latest(name, config),
        (None, _, None) => bail!("CRATE is required when creating a package"),
        (None, Some(_), Some(_)) => bail!("VERSION requires CRATE"),
    }
}

/// Resolves the latest crate release with `debcargo extract` and reads its Cargo identity.
fn resolve_latest(crate_name: &str, config: &PackageConfig) -> Result<Selection> {
    let stage = tempfile::tempdir().context("create latest-version staging directory")?;
    fs::create_dir(stage.path().join("overlay"))?;
    write_staged_config(config, stage.path())?;
    let output = Command::new("debcargo")
        .arg("extract")
        .arg("--config")
        .arg(stage.path().join("debcargo.toml"))
        .arg("--directory")
        .arg(stage.path().join("output"))
        .arg(crate_name)
        .current_dir(stage.path())
        .output()
        .context("run debcargo extract")?;
    if !output.status.success() {
        bail!(
            "debcargo extract failed:\n{}{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
    }
    let package = read_root_package(&stage.path().join("output"))?;
    if normalize_crate_name(crate_name) != normalize_crate_name(&package.name) {
        bail!(
            "debcargo selected crate {} instead of {crate_name}",
            package.name
        );
    }
    Ok(Selection {
        crate_name: package.name,
        version: package.version,
    })
}

/// Parses an exact Cargo semantic version and rejects requirement syntax.
fn parse_exact_version(version: &str) -> Result<Version> {
    Version::parse(version).with_context(|| format!("{version:?} is not an exact Cargo version"))
}

/// Converts Cargo semver to debcargo's Debian upstream-version syntax.
fn cargo_to_debian_version(version: &Version, repack_suffix: Option<&str>) -> String {
    let mut converted = format!("{}.{}.{}", version.major, version.minor, version.patch);
    if !version.pre.is_empty() {
        converted.push('~');
        converted.push_str(version.pre.as_str());
    }
    if let Some(repack_suffix) = repack_suffix {
        converted.push('+');
        converted.push_str(repack_suffix);
    }
    converted
}

/// Computes debcargo's Debian source name for a crate release.
fn crate_source_name(crate_name: &str, version: &Version, semver_suffix: bool) -> String {
    let mut source = format!("rust-{}", normalize_crate_name(crate_name));
    if semver_suffix {
        if version.major == 0 {
            source.push_str(&format!("-0.{}", version.minor));
        } else {
            source.push_str(&format!("-{}", version.major));
        }
    }
    source
}

/// Normalizes Cargo crate spelling to debcargo's dashed lowercase form.
fn normalize_crate_name(name: &str) -> String {
    name.replace('_', "-").to_lowercase()
}

/// Reads and validates the in-tree debcargo configuration.
fn read_package_config(path: &Path) -> Result<PackageConfig> {
    let contents = fs::read_to_string(path).with_context(|| format!("read {}", path.display()))?;
    read_package_config_text(&contents).with_context(|| format!("parse {}", path.display()))
}

/// Reads the package-identity subset of a debcargo configuration.
fn read_package_config_text(contents: &str) -> Result<PackageConfig> {
    let config: DocumentMut = contents.parse().context("parse debcargo configuration")?;
    if let Some(overlay) = config.get("overlay")
        && overlay.as_str() != Some(".")
    {
        bail!("overlay must be omitted or \".\"");
    }
    if config.get("crate_src_path").is_some() {
        bail!("crate_src_path is not supported by ubucargo package");
    }
    if let Some(item) = config.get("ubucargo") {
        let Some(table) = item.as_table() else {
            bail!("ubucargo must be a table");
        };
        if !table.is_empty() {
            bail!("[ubucargo] settings are not implemented yet");
        }
    }
    let semver_suffix = config
        .get("semver_suffix")
        .and_then(|item| item.as_bool())
        .unwrap_or(false);
    let repack_suffix = if let Some(item) = config.get("repack_suffix") {
        Some(
            item.as_str()
                .context("repack_suffix must be a string")?
                .to_owned(),
        )
    } else if config.get("excludes").is_some() {
        Some("ds".to_owned())
    } else {
        None
    };
    Ok(PackageConfig {
        contents: contents.to_owned(),
        semver_suffix,
        repack_suffix,
    })
}

/// Writes registry-backed staged configuration with a temporary overlay.
fn write_staged_config(config: &PackageConfig, stage: &Path) -> Result<()> {
    let mut document: DocumentMut = config.contents.parse()?;
    document.remove("ubucargo");
    document["overlay"] = value(require_utf8_path(&stage.join("overlay"))?);
    fs::write(stage.join("debcargo.toml"), document.to_string())?;
    Ok(())
}

/// Returns a path as UTF-8 for insertion into TOML.
fn require_utf8_path(path: &Path) -> Result<&str> {
    path.to_str()
        .with_context(|| format!("path is not valid UTF-8: {}", path.display()))
}

/// Builds the final debcargo staging tree with a prepared Ubuntu changelog.
fn stage_candidate(
    config: &PackageConfig,
    existing_debian: Option<&Path>,
    old_top: Option<&TopChangelog>,
    source_name: &str,
    upstream: &str,
    selection: &Selection,
) -> Result<TempDir> {
    let stage = tempfile::tempdir().context("create package staging directory")?;
    let overlay = stage.path().join("overlay");
    fs::create_dir(&overlay)?;
    if let Some(debian) = existing_debian {
        prepare_patch_overlay(debian, &overlay)?;
    }
    write_staged_config(config, stage.path())?;
    prepare_changelog(
        existing_debian.map(|debian| debian.join("changelog")),
        &overlay.join("changelog"),
        old_top,
        source_name,
        upstream,
        selection,
    )?;
    run_debcargo(stage.path(), selection)?;
    Ok(stage)
}

/// Copies the complete patch set into the debcargo overlay.
fn prepare_patch_overlay(debian: &Path, overlay: &Path) -> Result<()> {
    let patches = debian.join("patches");
    if !patches.is_dir() {
        return Ok(());
    }
    let overlay_patches = overlay.join("patches");
    let output = Command::new("cp")
        .arg("-a")
        .arg("--reflink=auto")
        .arg(format!("{}/.", patches.display()))
        .arg(&overlay_patches)
        .output()
        .context("run cp -a --reflink=auto")?;
    if !output.status.success() {
        bail!(
            "cp -a --reflink=auto failed:\n{}{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
    }
    Ok(())
}

/// Selects the `dch` action for old and candidate changelog state.
fn select_changelog_action(
    old: Option<&TopChangelog>,
    candidate_upstream: &str,
) -> ChangelogAction {
    let Some(old) = old else {
        return ChangelogAction::Create;
    };
    let unreleased = old.distribution == "UNRELEASED" || old.distribution == LEGACY_UNRELEASED;
    if unreleased && old.upstream == candidate_upstream {
        ChangelogAction::Append
    } else if !unreleased && old.upstream == candidate_upstream {
        ChangelogAction::Increment
    } else {
        ChangelogAction::NewVersion
    }
}

/// Prepares one changelog with `dch`, then normalizes provenance in its top entry.
fn prepare_changelog(
    old_path: Option<PathBuf>,
    staged_path: &Path,
    old_top: Option<&TopChangelog>,
    source_name: &str,
    upstream: &str,
    selection: &Selection,
) -> Result<()> {
    if let Some(old_path) = old_path {
        fs::copy(&old_path, staged_path)
            .with_context(|| format!("copy {} to {}", old_path.display(), staged_path.display()))?;
    }
    let version = format!("{upstream}-0ubuntu1");
    let provenance = format!(
        "Package {} {} from crates.io using debcargo {} and ubucargo {}.",
        selection.crate_name,
        selection.version,
        DEBCARGO_VERSION_NUMBER,
        env!("CARGO_PKG_VERSION")
    );
    let action = select_changelog_action(old_top, upstream);
    let mut command = Command::new("dch");
    command
        .arg("--no-conf")
        .arg("--vendor")
        .arg("Ubuntu")
        .arg("--changelog")
        .arg(staged_path)
        .arg("--check-dirname-level")
        .arg("0")
        .arg("--distribution")
        .arg("UNRELEASED")
        .arg("--force-distribution");
    match action {
        ChangelogAction::Create => {
            command
                .arg("--create")
                .arg("--package")
                .arg(source_name)
                .arg("--newversion")
                .arg(&version);
        }
        ChangelogAction::Increment => {
            command.arg("--increment");
        }
        ChangelogAction::NewVersion => {
            command.arg("--newversion").arg(&version);
        }
        ChangelogAction::Append => {
            command.arg("--append");
        }
    }
    let output = command.arg(&provenance).output().context("run dch")?;
    if !output.status.success() {
        bail!(
            "dch failed:\n{}{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
    }

    let contents = fs::read_to_string(staged_path)?;
    let contents = replace_provenance(&contents, &format!("  * {provenance}"));
    fs::write(staged_path, contents)?;
    let top = read_top_changelog(staged_path)?;
    if top.source != source_name || top.upstream != upstream {
        bail!(
            "prepared changelog identifies {} {}, expected {source_name} {upstream}",
            top.source,
            top.upstream
        );
    }
    Ok(())
}

/// Replaces all Ubucargo/debcargo provenance lines in the top changelog entry with one line.
fn replace_provenance(contents: &str, provenance: &str) -> String {
    let had_trailing_newline = contents.ends_with('\n');
    let mut lines: Vec<String> = contents.lines().map(str::to_owned).collect();
    if let Some(header) = lines.first_mut() {
        *header = header.replace(LEGACY_UNRELEASED, "UNRELEASED");
    }
    let mut top_end = lines.len();
    for (index, line) in lines.iter().enumerate().skip(1) {
        if !line.is_empty() && !line.starts_with(char::is_whitespace) {
            top_end = index;
            break;
        }
    }

    let mut rewritten = Vec::new();
    let mut found = false;
    let mut index = 0;
    while index < top_end {
        let trimmed = lines[index].trim_start();
        if trimmed.starts_with("* Package ") && trimmed.contains(" using debcargo ") {
            if !found {
                rewritten.push(provenance.to_owned());
                found = true;
            }
            index += 1;
            while index < top_end && lines[index].starts_with("    ") {
                index += 1;
            }
            continue;
        }
        rewritten.push(lines[index].clone());
        index += 1;
    }
    rewritten.extend(lines.into_iter().skip(top_end));
    lines = rewritten;
    if !found {
        let insert = if lines.get(1).is_some_and(|line| line.is_empty()) {
            2
        } else {
            1
        };
        lines.insert(insert, provenance.to_owned());
    }
    let mut result = lines.join("\n");
    if had_trailing_newline {
        result.push('\n');
    }
    result
}

/// Runs final debcargo generation for one exact selected release.
fn run_debcargo(stage: &Path, selection: &Selection) -> Result<()> {
    let output = Command::new("debcargo")
        .arg("package")
        .arg("--config")
        .arg(stage.join("debcargo.toml"))
        .arg("--directory")
        .arg(stage.join("output"))
        .arg("--no-overlay-write-back")
        .arg("--changelog-ready")
        .arg(&selection.crate_name)
        .arg(&selection.version)
        .current_dir(stage)
        .output()
        .context("run debcargo package")?;
    if !output.status.success() {
        bail!(
            "debcargo package failed:\n{}{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
    }
    Ok(())
}

/// Validates staged source identity, Cargo identity, essential packaging, and orig naming.
fn validate_output(
    stage: &Path,
    expected_source: &str,
    expected_upstream: &str,
    requested_name: &str,
    requested_version: &str,
) -> Result<GeneratedOutput> {
    let source = stage.join("output");
    for path in [
        source.join("Cargo.toml"),
        source.join("debian/changelog"),
        source.join("debian/control"),
        source.join("debian/rules"),
        source.join("debian/source/format"),
    ] {
        if !path.is_file() {
            bail!("debcargo produced no {}", path.display());
        }
    }

    let package = read_root_package(&source)?;
    if normalize_crate_name(requested_name) != normalize_crate_name(&package.name) {
        bail!(
            "debcargo selected crate {} instead of {requested_name}",
            package.name
        );
    }
    if package.version != requested_version {
        bail!(
            "debcargo selected {} {} instead of requested version {requested_version}",
            package.name,
            package.version
        );
    }

    let control = fs::read_to_string(source.join("debian/control"))?;
    let mut debian_source = None;
    for line in control.lines() {
        if let Some(value) = line.strip_prefix("Source:") {
            debian_source = Some(value.trim().to_owned());
            break;
        }
    }
    let debian_source = debian_source.context("generated debian/control has no Source field")?;
    if debian_source != expected_source {
        bail!("debcargo produced Debian source {debian_source}, expected {expected_source}");
    }
    if fs::read(source.join("debian/changelog"))? != fs::read(stage.join("overlay/changelog"))? {
        bail!("debcargo changed the prepared changelog despite --changelog-ready");
    }

    let expected_orig = format!("{expected_source}_{expected_upstream}.orig.tar.gz");
    let mut origs = Vec::new();
    for entry in fs::read_dir(stage)? {
        let path = entry?.path();
        if path
            .file_name()
            .and_then(OsStr::to_str)
            .is_some_and(|name| name.ends_with(".orig.tar.gz"))
        {
            origs.push(path);
        }
    }
    if origs.len() != 1 {
        bail!(
            "debcargo produced {} orig tarballs; expected one",
            origs.len()
        );
    }
    let orig = origs.pop().unwrap();
    if orig.file_name() != Some(OsStr::new(&expected_orig)) {
        bail!(
            "debcargo produced orig {}, expected {expected_orig}",
            orig.display()
        );
    }
    Ok(GeneratedOutput {
        source,
        orig,
        debian_source,
    })
}

/// Uses Cargo to identify the package defined by the root manifest.
pub(crate) fn read_root_package(root: &Path) -> Result<MetadataPackage> {
    let manifest = root.join("Cargo.toml").canonicalize()?;
    let output = Command::new("cargo")
        .args([
            "metadata",
            "--offline",
            "--no-deps",
            "--format-version",
            "1",
            "--manifest-path",
        ])
        .arg(&manifest)
        .output()
        .context("run cargo metadata")?;
    if !output.status.success() {
        bail!(
            "cargo metadata failed:\n{}",
            String::from_utf8_lossy(&output.stderr).trim()
        );
    }
    let metadata: Metadata = serde_json::from_slice(&output.stdout)?;
    metadata
        .packages
        .into_iter()
        .find(|package| {
            package
                .manifest_path
                .canonicalize()
                .is_ok_and(|path| path == manifest)
        })
        .with_context(|| format!("{} does not contain a root [package]", manifest.display()))
}

/// Rejects debcargo versions not covered by the current compatibility target.
pub(crate) fn check_debcargo_version() -> Result<()> {
    let output = Command::new("debcargo")
        .arg("--version")
        .output()
        .context("run debcargo --version")?;
    if !output.status.success() {
        bail!("debcargo --version failed");
    }
    let actual = String::from_utf8_lossy(&output.stdout).trim().to_owned();
    if actual != DEBCARGO_VERSION {
        bail!("unsupported {actual}; this release requires {DEBCARGO_VERSION}");
    }
    Ok(())
}

/// Parses only the first Debian changelog header.
fn read_top_changelog(path: &Path) -> Result<TopChangelog> {
    let contents = fs::read_to_string(path).with_context(|| format!("read {}", path.display()))?;
    parse_top_changelog(&contents).with_context(|| format!("parse {}", path.display()))
}

/// Parses the source, version, distribution, and upstream version from a changelog header.
fn parse_top_changelog(contents: &str) -> Result<TopChangelog> {
    let header = contents.lines().next().context("changelog is empty")?;
    let (source, rest) = header
        .split_once(" (")
        .context("invalid changelog header")?;
    let (version, rest) = rest.split_once(") ").context("invalid changelog version")?;
    let (distribution, _) = rest
        .split_once(';')
        .context("invalid changelog distribution")?;
    if source.is_empty() || version.is_empty() || distribution.trim().is_empty() {
        bail!("invalid changelog header");
    }
    let upstream = debian_upstream_version(version)?;
    Ok(TopChangelog {
        source: source.to_owned(),
        version: version.to_owned(),
        upstream,
        distribution: distribution.trim().to_owned(),
    })
}

/// Extracts the epoch-free upstream portion from a Debian source version.
fn debian_upstream_version(version: &str) -> Result<String> {
    let without_epoch = version.split_once(':').map_or(version, |(_, value)| value);
    let (upstream, revision) = without_epoch
        .rsplit_once('-')
        .context("Debian source version has no revision")?;
    if upstream.is_empty() || revision.is_empty() {
        bail!("invalid Debian source version {version}");
    }
    Ok(upstream.to_owned())
}

/// Requires the top changelog upstream to describe the current root Cargo release.
fn validate_top_changelog(top: &TopChangelog, package: &MetadataPackage) -> Result<()> {
    let version = parse_exact_version(&package.version)?;
    let cargo_upstream = cargo_to_debian_version(&version, None);
    if top.upstream != cargo_upstream
        && !top
            .upstream
            .strip_prefix(&cargo_upstream)
            .is_some_and(|suffix| suffix.starts_with('+') && suffix.len() > 1)
    {
        bail!(
            "top changelog upstream {} does not describe root Cargo version {}",
            top.upstream,
            package.version
        );
    }
    Ok(())
}

/// Finds the old orig locally or downloads and verifies the exact Launchpad source.
fn acquire_old_orig(root: &Path, top: &TopChangelog) -> Result<OrigBaseline> {
    let parent = root.parent().context("package root has no parent")?;
    let expected_name = format!("{}_{}.orig.tar.gz", top.source, top.upstream);
    let local = parent.join(&expected_name);
    if local.is_file() {
        return Ok(OrigBaseline {
            path: local,
            _temporary: None,
        });
    }

    let download = tempfile::tempdir().context("create orig download directory")?;
    let output = Command::new("pull-lp-source")
        .arg("--download-only")
        .arg(&top.source)
        .arg(&top.version)
        .current_dir(download.path())
        .output()
        .context("run pull-lp-source")?;
    if !output.status.success() {
        bail!(
            "pull-lp-source failed:\n{}{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
    }

    let orig = validate_download_directory(download.path(), top)?;
    Ok(OrigBaseline {
        path: orig,
        _temporary: Some(download),
    })
}

/// Locates and verifies the single downloaded source description and expected orig.
fn validate_download_directory(directory: &Path, top: &TopChangelog) -> Result<PathBuf> {
    let mut dscs = Vec::new();
    for entry in fs::read_dir(directory)? {
        let path = entry?.path();
        if path.extension() == Some(OsStr::new("dsc")) {
            dscs.push(path);
        }
    }
    if dscs.len() != 1 {
        bail!("pull-lp-source produced {} .dsc files", dscs.len());
    }
    let expected_name = format!("{}_{}.orig.tar.gz", top.source, top.upstream);
    let orig = directory.join(expected_name);
    verify_downloaded_orig(&dscs[0], &orig, &top.source, &top.version)?;
    Ok(orig)
}

/// Verifies downloaded source identity, orig filename, size, and SHA-256 from its `.dsc`.
fn verify_downloaded_orig(
    dsc: &Path,
    orig: &Path,
    expected_source: &str,
    expected_version: &str,
) -> Result<()> {
    let contents = fs::read_to_string(dsc).with_context(|| format!("read {}", dsc.display()))?;
    if read_dsc_field(&contents, "Source") != Some(expected_source)
        || read_dsc_field(&contents, "Version") != Some(expected_version)
    {
        bail!("{} has unexpected source identity", dsc.display());
    }
    let expected_name = orig.file_name().context("orig path has no file name")?;
    let expected_name = expected_name.to_string_lossy();
    let mut in_checksums = false;
    let mut checksum = None;
    for line in contents.lines() {
        if line == "Checksums-Sha256:" {
            in_checksums = true;
            continue;
        }
        if in_checksums && !line.starts_with(' ') {
            break;
        }
        if !in_checksums {
            continue;
        }
        let fields: Vec<&str> = line.split_whitespace().collect();
        if fields.len() == 3 && fields[2] == expected_name {
            checksum = Some((fields[0], fields[1]));
        }
    }
    let (expected_hash, expected_size) =
        checksum.context(".dsc does not name the expected orig")?;
    let size = fs::metadata(orig)
        .with_context(|| format!("inspect {}", orig.display()))?
        .len();
    if expected_size
        .parse::<u64>()
        .context("parse .dsc orig size")?
        != size
    {
        bail!("downloaded orig size does not match .dsc");
    }
    let output = Command::new("sha256sum")
        .arg(orig)
        .output()
        .context("run sha256sum")?;
    if !output.status.success() {
        bail!("sha256sum failed for {}", orig.display());
    }
    let actual = String::from_utf8_lossy(&output.stdout);
    let actual = actual.split_whitespace().next().unwrap_or_default();
    if actual != expected_hash {
        bail!("downloaded orig checksum does not match .dsc");
    }
    Ok(())
}

/// Reads one simple RFC822 field from a `.dsc` file.
fn read_dsc_field<'a>(contents: &'a str, field: &str) -> Option<&'a str> {
    let prefix = format!("{field}:");
    for line in contents.lines() {
        if let Some(value) = line.strip_prefix(&prefix) {
            return Some(value.trim());
        }
    }
    None
}

/// Extracts an orig tarball as the pristine merge baseline.
fn extract_orig(orig: &Path, destination: &Path) -> Result<()> {
    let output = Command::new("tar")
        .arg("--extract")
        .arg("--file")
        .arg(orig)
        .arg("--directory")
        .arg(destination)
        .arg("--strip-components=1")
        .output()
        .context("run tar")?;
    if !output.status.success() {
        bail!(
            "could not extract {}:\n{}{}",
            orig.display(),
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
    }
    Ok(())
}

/// Scans a deterministic tree while rejecting special files and optionally excluding `debian/`.
fn scan_tree(root: &Path, exclude_debian: bool) -> Result<BTreeMap<PathBuf, TreeNode>> {
    let mut tree = BTreeMap::new();
    let mut directories = vec![PathBuf::new()];
    while let Some(relative) = directories.pop() {
        let directory = root.join(&relative);
        let mut entries = Vec::new();
        for entry in
            fs::read_dir(&directory).with_context(|| format!("read {}", directory.display()))?
        {
            entries.push(entry?);
        }
        entries.sort_by_key(|entry| entry.file_name());
        for entry in entries.into_iter().rev() {
            let path = relative.join(entry.file_name());
            if exclude_debian && path == Path::new("debian") {
                continue;
            }
            let metadata = fs::symlink_metadata(entry.path())?;
            let file_type = metadata.file_type();
            if file_type.is_dir() {
                tree.insert(
                    path.clone(),
                    TreeNode::Directory(metadata.permissions().mode() & 0o7777),
                );
                directories.push(path);
            } else if file_type.is_file() {
                tree.insert(
                    path,
                    TreeNode::File(FileState {
                        contents: fs::read(entry.path())?,
                        mode: metadata.permissions().mode() & 0o7777,
                    }),
                );
            } else if file_type.is_symlink() {
                tree.insert(path, TreeNode::Symlink(fs::read_link(entry.path())?));
            } else {
                bail!(
                    "source tree contains special file {}",
                    entry.path().display()
                );
            }
        }
    }
    Ok(tree)
}

/// Builds the complete conservative three-tree source merge.
fn build_source_plan(
    base: &BTreeMap<PathBuf, TreeNode>,
    old: &BTreeMap<PathBuf, TreeNode>,
    new: &BTreeMap<PathBuf, TreeNode>,
    force: bool,
) -> Result<SourcePlan> {
    let mut all = BTreeSet::new();
    all.extend(base.keys().cloned());
    all.extend(old.keys().cloned());
    all.extend(new.keys().cloned());
    let mut after = BTreeMap::new();
    let mut conflicts = Vec::new();
    for path in &all {
        let base_state = base.get(path);
        let old_state = old.get(path);
        let new_state = new.get(path);
        let selected = if old_state == base_state {
            new_state.cloned()
        } else if old_state == new_state || (base_state.is_none() && new_state.is_none()) {
            old_state.cloned()
        } else if force {
            new_state.cloned()
        } else {
            conflicts.push(path.clone());
            old_state.cloned()
        };
        after.insert(path.clone(), selected);
    }
    if !conflicts.is_empty() {
        let names: Vec<String> = conflicts
            .iter()
            .map(|path| path.display().to_string())
            .collect();
        bail!("source conflicts: {}", names.join(", "));
    }

    let mut blocked = Vec::new();
    for path in &all {
        if after.get(path).and_then(Option::as_ref).is_none() {
            continue;
        }
        let mut ancestor = path.parent();
        while let Some(parent) = ancestor {
            if parent.as_os_str().is_empty() {
                break;
            }
            if !matches!(after.get(parent), Some(Some(TreeNode::Directory(_)))) {
                blocked.push(path.clone());
                break;
            }
            ancestor = parent.parent();
        }
    }
    if !blocked.is_empty() && !force {
        let names: Vec<String> = blocked
            .iter()
            .map(|path| path.display().to_string())
            .collect();
        bail!("structural source conflicts: {}", names.join(", "));
    }
    for path in blocked {
        after.insert(path, None);
    }

    let mut paths = BTreeMap::new();
    for path in all {
        paths.insert(
            path.clone(),
            (old.get(&path).cloned(), after.remove(&path).unwrap()),
        );
    }
    Ok(SourcePlan { paths })
}

/// Rejects unrefreshed top-patch edits and reports whether any patches are applied.
fn check_patch_state(source: &Path) -> Result<bool> {
    let path = source.join(".pc/applied-patches");
    let contents = match fs::read_to_string(&path) {
        Ok(contents) => contents,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(false),
        Err(error) => return Err(error).with_context(|| format!("read {}", path.display())),
    };
    if !contents.lines().any(|line| !line.trim().is_empty()) {
        return Ok(false);
    }
    let output = Command::new("quilt")
        .args(["diff", "--quiltrc=-", "-z", "--no-timestamps", "--no-index"])
        .env("QUILT_PATCHES", "debian/patches")
        .current_dir(source)
        .output()
        .context("run quilt diff -z")?;
    if !output.status.success() {
        bail!(
            "could not inspect the current quilt patch:\n{}{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
    }
    if !output.stdout.is_empty() {
        bail!("the current quilt patch has unrefreshed changes; run `quilt refresh`");
    }
    Ok(true)
}

/// Reports whether generated automatic patches or their series change.
fn generated_patch_changes(plan: &crate::materialize::Plan) -> bool {
    for path in &plan.paths {
        let generated_patch_changed =
            path.path == Path::new("debian/patches/series") || is_auto_patch(&path.path);
        if generated_patch_changed && path.old != path.primary_after {
            return true;
        }
    }
    false
}

/// Reads fresh debcargo outputs proposed for reconciliation.
fn read_generated_candidates(stage: &Path) -> Result<BTreeMap<PathBuf, FileState>> {
    let output_debian = stage.join("output/debian");
    if !output_debian.is_dir() {
        bail!("debcargo produced no debian directory");
    }
    let mut generated = BTreeMap::new();
    let mut output_paths = BTreeSet::new();
    collect_output_paths(&output_debian, &output_debian, &mut output_paths)?;
    for path in output_paths {
        if is_package_managed(&path) {
            let state = read_state(&stage.join("output").join(&path))?
                .with_context(|| format!("missing generated {}", path.display()))?;
            generated.insert(path, state);
        } else if !is_expected_unmanaged_output(&path) {
            eprintln!(
                "warning: ignoring unrecognized debcargo output {}",
                path.display()
            );
        }
    }
    Ok(generated)
}

/// Adds file-like debcargo output paths to a package-relative result set.
pub(crate) fn collect_output_paths(
    directory: &Path,
    root: &Path,
    paths: &mut BTreeSet<PathBuf>,
) -> Result<()> {
    for entry in fs::read_dir(directory).with_context(|| format!("read {}", directory.display()))? {
        let entry = entry?;
        let path = entry.path();
        if fs::symlink_metadata(&path)?.file_type().is_dir() {
            collect_output_paths(&path, root, paths)?;
        } else {
            paths.insert(Path::new("debian").join(path.strip_prefix(root)?));
        }
    }
    Ok(())
}

/// Collects paths reconciled by generated-file hint rules.
fn collect_managed_paths(
    debian: &Path,
    generated: &BTreeMap<PathBuf, FileState>,
) -> Result<BTreeSet<PathBuf>> {
    let mut managed = BTreeSet::new();
    for path in PACKAGE_MANAGED_PATHS {
        managed.insert(PathBuf::from(path));
    }
    for path in generated.keys() {
        managed.insert(path.clone());
    }
    for entry in fs::read_dir(debian)? {
        let name = entry?.file_name();
        let name = name.to_string_lossy();
        let primary = name.strip_suffix(".debcargo.hint").unwrap_or(&name);
        let primary = PathBuf::from("debian").join(primary);
        if is_feature_override(&primary) {
            managed.insert(primary);
        }
    }
    let auto_dir = debian.join("patches/auto");
    if auto_dir.is_dir() {
        let mut auto_paths = BTreeSet::new();
        collect_output_paths(&auto_dir, debian, &mut auto_paths)?;
        for mut path in auto_paths {
            let primary = path
                .file_name()
                .unwrap()
                .to_string_lossy()
                .strip_suffix(".debcargo.hint")
                .map(str::to_owned);
            if let Some(primary) = primary {
                path.set_file_name(primary);
            }
            if is_auto_patch(&path) {
                managed.insert(path);
            }
        }
    }
    Ok(managed)
}

/// Reports whether the package command recognizes a staged path as managed output.
pub(crate) fn is_package_managed(path: &Path) -> bool {
    PACKAGE_MANAGED_PATHS
        .iter()
        .any(|managed| path == Path::new(managed))
        || is_feature_override(path)
        || is_auto_patch(path)
}

/// Reports whether a path belongs to the dynamic feature-package override namespace.
fn is_feature_override(path: &Path) -> bool {
    path.parent() == Some(Path::new("debian"))
        && path.file_name().is_some_and(|name| {
            let name = name.to_string_lossy();
            name.starts_with("librust-") && name.ends_with(".lintian-overrides")
        })
}

/// Reports whether a path belongs to debcargo's generated auto-patch namespace.
fn is_auto_patch(path: &Path) -> bool {
    path.starts_with("debian/patches/auto")
        && !path
            .file_name()
            .is_some_and(|name| name.to_string_lossy().ends_with(".debcargo.hint"))
}

/// Reports whether debcargo is expected to emit a path that Ubucargo intentionally ignores.
fn is_expected_unmanaged_output(path: &Path) -> bool {
    path.starts_with("debian/patches")
        || EXPECTED_UNMANAGED_OUTPUTS
            .iter()
            .any(|expected| path == Path::new(expected))
}

/// Builds the patch-series update from debcargo's merged output.
fn build_patch_series_plan(debian: &Path, stage: &Path) -> Result<PathPlan> {
    Ok(PathPlan {
        path: PathBuf::from("debian/patches/series"),
        old: read_state(&debian.join("patches/series"))?,
        base: None,
        primary_after: read_state(&stage.join("output/debian/patches/series"))?,
        hint_after: None,
        tracks_hint: false,
        overridden: false,
        ambiguous: false,
    })
}

/// Adds Ubucargo configuration and generated-file baselines to a new staged package.
fn initialize_package(source: &Path) -> Result<()> {
    let debian = source.join("debian");
    fs::write(debian.join("debcargo.toml"), "[ubucargo]\n")?;
    let mut paths = BTreeSet::new();
    collect_output_paths(&debian, &debian, &mut paths)?;
    for path in paths {
        if !is_package_managed(&path) {
            continue;
        }
        let primary = debian.join(path.strip_prefix("debian")?);
        let hint = make_hint_path(&primary);
        fs::copy(&primary, &hint)?;
    }
    Ok(())
}

/// Rejects any existing filesystem entry, including a broken symbolic link.
fn ensure_destination_absent(path: &Path) -> Result<()> {
    match fs::symlink_metadata(path) {
        Ok(_) => bail!("destination already exists: {}", path.display()),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(error) => Err(error).with_context(|| format!("inspect {}", path.display())),
    }
}

/// Reports whether a candidate orig must be installed and rejects mismatching collisions.
fn validate_candidate_orig(candidate: &Path, destination: &Path) -> Result<bool> {
    match fs::symlink_metadata(destination) {
        Ok(metadata) if metadata.is_file() => {
            if files_equal(candidate, destination)? {
                Ok(false)
            } else {
                bail!(
                    "existing orig {} does not match the candidate",
                    destination.display()
                )
            }
        }
        Ok(_) => bail!(
            "orig destination is not a regular file: {}",
            destination.display()
        ),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(true),
        Err(error) => Err(error).with_context(|| format!("inspect {}", destination.display())),
    }
}

/// Compares two files without loading tarballs into memory.
fn files_equal(first: &Path, second: &Path) -> Result<bool> {
    if fs::metadata(first)?.len() != fs::metadata(second)?.len() {
        return Ok(false);
    }
    let mut first = File::open(first)?;
    let mut second = File::open(second)?;
    let mut first_buffer = [0_u8; 64 * 1024];
    let mut second_buffer = [0_u8; 64 * 1024];
    loop {
        let first_read = first.read(&mut first_buffer)?;
        let second_read = second.read(&mut second_buffer)?;
        if first_read != second_read || first_buffer[..first_read] != second_buffer[..second_read] {
            return Ok(false);
        }
        if first_read == 0 {
            return Ok(true);
        }
    }
}

/// Installs an orig tarball atomically without replacing an existing path.
fn install_orig(candidate: &Path, destination: &Path) -> Result<()> {
    let parent = destination
        .parent()
        .context("orig destination has no parent")?;
    fs::create_dir_all(parent)?;
    let mut temporary = NamedTempFile::new_in(parent)?;
    let mut source = File::open(candidate)?;
    std::io::copy(&mut source, &mut temporary)?;
    temporary
        .as_file()
        .set_permissions(fs::metadata(candidate)?.permissions())?;
    temporary
        .persist_noclobber(destination)
        .map_err(|error| error.error)
        .with_context(|| format!("install {}", destination.display()))?;
    Ok(())
}

/// Atomically writes one regular file and its Unix mode.
fn install_regular_file(path: &Path, state: &FileState) -> Result<()> {
    let parent = path.parent().context("file destination has no parent")?;
    fs::create_dir_all(parent)?;
    let mut temporary = NamedTempFile::new_in(parent)?;
    temporary.write_all(&state.contents)?;
    temporary
        .as_file()
        .set_permissions(fs::Permissions::from_mode(state.mode))?;
    temporary
        .persist(path)
        .map_err(|error| error.error)
        .with_context(|| format!("replace {}", path.display()))?;
    Ok(())
}

/// Copies a complete staged tree into place with one final directory rename.
fn install_new_tree(candidate: &Path, destination: &Path) -> Result<()> {
    let parent = destination
        .parent()
        .context("source destination has no parent")?;
    let temporary = tempfile::Builder::new()
        .prefix(".ubucargo-package-")
        .tempdir_in(parent)?;
    let copied = temporary.path().join("source");
    fs::create_dir(&copied)?;
    let output = Command::new("cp")
        .arg("-a")
        .arg("--reflink=auto")
        .arg(format!("{}/.", candidate.display()))
        .arg(&copied)
        .output()
        .context("run cp -a --reflink=auto")?;
    if !output.status.success() {
        bail!(
            "cp -a --reflink=auto failed:\n{}{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
    }
    fs::rename(&copied, destination)
        .with_context(|| format!("install {}", destination.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Creates a compact file node for source-merge tests.
    fn file(value: &str) -> TreeNode {
        TreeNode::File(FileState {
            contents: value.as_bytes().to_vec(),
            mode: 0o644,
        })
    }

    #[test]
    /// Verifies exact Cargo-to-Debian upstream conversion.
    fn converts_cargo_versions() {
        assert_eq!(
            cargo_to_debian_version(&Version::parse("1.2.3-alpha.1+build").unwrap(), None),
            "1.2.3~alpha.1"
        );
        assert_eq!(
            cargo_to_debian_version(&Version::parse("0.4.0").unwrap(), Some("ds")),
            "0.4.0+ds"
        );
        assert!(parse_exact_version("^1.2").is_err());
    }

    #[test]
    /// Verifies top changelog parsing and Cargo-version validation with a repack suffix.
    fn validates_top_changelog_identity() {
        let top = parse_top_changelog("rust-example (1.2.3+ds-0ubuntu1) noble; urgency=medium\n")
            .unwrap();
        let package = MetadataPackage {
            name: "example".to_owned(),
            version: "1.2.3".to_owned(),
            manifest_path: PathBuf::new(),
        };
        validate_top_changelog(&top, &package).unwrap();
        assert_eq!(top.source, "rust-example");
        assert_eq!(top.upstream, "1.2.3+ds");
    }

    #[test]
    /// Verifies changelog action selection for released and unreleased entries.
    fn selects_changelog_actions() {
        let mut top =
            parse_top_changelog("rust-example (1.2.3-0ubuntu1) noble; urgency=medium\n").unwrap();
        assert_eq!(
            select_changelog_action(Some(&top), "1.2.3"),
            ChangelogAction::Increment
        );
        assert_eq!(
            select_changelog_action(Some(&top), "2.0.0"),
            ChangelogAction::NewVersion
        );
        top.distribution = "UNRELEASED".to_owned();
        assert_eq!(
            select_changelog_action(Some(&top), "1.2.3"),
            ChangelogAction::Append
        );
        assert_eq!(
            select_changelog_action(None, "1.2.3"),
            ChangelogAction::Create
        );
    }

    #[test]
    /// Verifies provenance replacement and legacy unreleased normalization.
    fn replaces_provenance_once() {
        let old = concat!(
            "rust-example (1.0.0-1) UNRELEASED-FIXME-AUTOGENERATED-DEBCARGO; urgency=medium\n",
            "\n",
            "  * Package example 1.0.0 from crates.io using debcargo 2.7.0\n",
            "    with an old wrapped continuation.\n",
            "  * local change\n",
            "  * Package example 1.0.0 from crates.io using debcargo 2.8.0 and ubucargo 0.0.1.\n",
            "\n",
            " -- A <a@example.com>  Mon, 01 Jan 2024 00:00:00 +0000\n"
        );
        let new = replace_provenance(
            old,
            "  * Package example 1.0.0 from crates.io using debcargo 2.8.4 and ubucargo 0.1.0.",
        );
        assert!(new.contains(") UNRELEASED;"));
        assert_eq!(new.matches("using debcargo").count(), 1);
        assert!(new.contains("  * local change"));
    }

    #[test]
    /// Verifies the complete non-conflicting source merge table.
    fn merges_source_states() {
        let base = BTreeMap::from([
            (PathBuf::from("unchanged"), file("base")),
            (PathBuf::from("removed"), file("base")),
            (PathBuf::from("upstream"), file("base")),
            (PathBuf::from("same"), file("old-new")),
        ]);
        let old = BTreeMap::from([
            (PathBuf::from("unchanged"), file("base")),
            (PathBuf::from("removed"), file("base")),
            (PathBuf::from("upstream"), file("base")),
            (PathBuf::from("same"), file("old-new")),
            (PathBuf::from("local"), file("local")),
        ]);
        let new = BTreeMap::from([
            (PathBuf::from("unchanged"), file("new")),
            (PathBuf::from("upstream"), file("new")),
            (PathBuf::from("same"), file("old-new")),
            (PathBuf::from("added"), file("new")),
        ]);
        let plan = build_source_plan(&base, &old, &new, false).unwrap();
        assert_eq!(plan.paths[Path::new("unchanged")].1, Some(file("new")));
        assert_eq!(plan.paths[Path::new("removed")].1, None);
        assert_eq!(plan.paths[Path::new("local")].1, Some(file("local")));
        assert_eq!(plan.paths[Path::new("added")].1, Some(file("new")));
    }

    #[test]
    /// Verifies conflict refusal, forced replacement, and structural descendant pruning.
    fn handles_source_conflicts_and_force() {
        let base = BTreeMap::from([(PathBuf::from("path"), file("base"))]);
        let old = BTreeMap::from([(PathBuf::from("path"), file("local"))]);
        let new = BTreeMap::from([(PathBuf::from("path"), file("new"))]);
        assert!(build_source_plan(&base, &old, &new, false).is_err());
        let plan = build_source_plan(&base, &old, &new, true).unwrap();
        assert_eq!(plan.paths[Path::new("path")].1, Some(file("new")));

        let base = BTreeMap::from([(PathBuf::from("dir"), TreeNode::Directory(0o755))]);
        let old = BTreeMap::from([
            (PathBuf::from("dir"), TreeNode::Directory(0o755)),
            (PathBuf::from("dir/local"), file("local")),
        ]);
        let new = BTreeMap::new();
        assert!(build_source_plan(&base, &old, &new, false).is_err());
        let plan = build_source_plan(&base, &old, &new, true).unwrap();
        assert_eq!(plan.paths[Path::new("dir/local")].1, None);
    }

    #[test]
    /// Verifies source reconciliation preserves modes and accepts upstream file-type changes.
    fn handles_modes_and_symlink_changes() {
        let base = BTreeMap::from([
            (PathBuf::from("mode"), file("same")),
            (
                PathBuf::from("kind"),
                TreeNode::Symlink(PathBuf::from("old-target")),
            ),
        ]);
        let old = base.clone();
        let new = BTreeMap::from([
            (
                PathBuf::from("mode"),
                TreeNode::File(FileState {
                    contents: b"same".to_vec(),
                    mode: 0o755,
                }),
            ),
            (PathBuf::from("kind"), file("now a file")),
        ]);
        let plan = build_source_plan(&base, &old, &new, false).unwrap();
        assert_eq!(
            plan.paths[Path::new("mode")].1,
            new.get(Path::new("mode")).cloned()
        );
        assert_eq!(
            plan.paths[Path::new("kind")].1,
            new.get(Path::new("kind")).cloned()
        );
    }

    #[test]
    /// Verifies explicit nonexistent directories select clean creation even inside a package.
    fn selects_clean_explicit_destination() {
        let root = tempfile::tempdir().unwrap();
        fs::create_dir(root.path().join("debian")).unwrap();
        fs::write(root.path().join("debian/debcargo.toml"), "").unwrap();
        let target = resolve_target(root.path(), Some(Path::new("new-package")), true).unwrap();
        assert_eq!(
            target,
            Target::New {
                parent: root.path().to_path_buf(),
                requested: Some(root.path().join("new-package")),
            }
        );
    }

    #[test]
    /// Verifies implicit mode finds a parent package or creates in the start directory.
    fn selects_implicit_target_mode() {
        let root = tempfile::tempdir().unwrap();
        fs::create_dir_all(root.path().join("debian")).unwrap();
        fs::write(root.path().join("debian/debcargo.toml"), "").unwrap();
        let nested = root.path().join("a/b");
        fs::create_dir_all(&nested).unwrap();
        assert_eq!(
            resolve_target(&nested, None, false).unwrap(),
            Target::Existing(root.path().to_path_buf())
        );

        let clean = tempfile::tempdir().unwrap();
        assert_eq!(
            resolve_target(clean.path(), None, true).unwrap(),
            Target::New {
                parent: clean.path().to_path_buf(),
                requested: None,
            }
        );
        assert!(resolve_target(clean.path(), None, false).is_err());
    }

    #[test]
    /// Verifies local orig discovery and mismatching candidate refusal.
    fn finds_local_orig_and_rejects_candidate_collision() {
        let parent = tempfile::tempdir().unwrap();
        let root = parent.path().join("rust-example");
        fs::create_dir(&root).unwrap();
        let orig = parent.path().join("rust-example_1.0.0.orig.tar.gz");
        fs::write(&orig, "orig").unwrap();
        let top = TopChangelog {
            source: "rust-example".to_owned(),
            version: "1.0.0-0ubuntu1".to_owned(),
            upstream: "1.0.0".to_owned(),
            distribution: "noble".to_owned(),
        };
        assert_eq!(acquire_old_orig(&root, &top).unwrap().path, orig);

        let candidate = parent.path().join("candidate");
        fs::write(&candidate, "different").unwrap();
        assert!(validate_candidate_orig(&candidate, &orig).is_err());
    }

    #[test]
    /// Verifies downloaded orig discovery, checksum validation, and missing-base rejection.
    fn validates_downloaded_orig_fixture() {
        let directory = tempfile::tempdir().unwrap();
        let top = TopChangelog {
            source: "rust-example".to_owned(),
            version: "1.0.0-0ubuntu1".to_owned(),
            upstream: "1.0.0".to_owned(),
            distribution: "noble".to_owned(),
        };
        assert!(validate_download_directory(directory.path(), &top).is_err());

        let orig = directory.path().join("rust-example_1.0.0.orig.tar.gz");
        fs::write(&orig, "orig").unwrap();
        let dsc = directory.path().join("rust-example_1.0.0-0ubuntu1.dsc");
        fs::write(
            &dsc,
            concat!(
                "Source: rust-example\n",
                "Version: 1.0.0-0ubuntu1\n",
                "Checksums-Sha256:\n",
                " 14e0ffdc8215c81da0cde40f581237ee35177ddac4f1fc7613cad3004798d25f 4 rust-example_1.0.0.orig.tar.gz\n",
            ),
        )
        .unwrap();
        assert_eq!(
            validate_download_directory(directory.path(), &top).unwrap(),
            orig
        );

        fs::write(
            dsc,
            concat!(
                "Source: rust-example\n",
                "Version: 1.0.0-0ubuntu1\n",
                "Checksums-Sha256:\n",
                " deadbeef 4 rust-example_1.0.0.orig.tar.gz\n",
            ),
        )
        .unwrap();
        assert!(validate_download_directory(directory.path(), &top).is_err());
    }

    #[test]
    /// Verifies new-package initialization creates hints only for managed output.
    fn initializes_config_and_managed_hints() {
        let root = tempfile::tempdir().unwrap();
        fs::create_dir_all(root.path().join("debian/patches/auto")).unwrap();
        fs::write(root.path().join("debian/control"), "control").unwrap();
        fs::write(root.path().join("debian/changelog"), "changelog").unwrap();
        fs::write(
            root.path().join("debian/patches/auto/change.patch"),
            "patch",
        )
        .unwrap();
        initialize_package(root.path()).unwrap();
        assert_eq!(
            fs::read_to_string(root.path().join("debian/debcargo.toml")).unwrap(),
            "[ubucargo]\n"
        );
        assert!(root.path().join("debian/control.debcargo.hint").is_file());
        assert!(!root.path().join("debian/changelog.debcargo.hint").exists());
    }
}
